services:
    backend:
        build: ./backend
        ports:
            - '8181:8181'
        # volumes:
        #     - ./backend:/app
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        # volumes:
        #     - ./frontend:/app
        #     - ./app/node_modules
